### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by corxit** [AustinSMU/PRECISION-M3800-OSX#1]
Hi AustinSMU,

I have followed your steps, I am so shocked by the amazing method!! Thank you a lot and the others contributed this. I would like to feedback you some omissions of the commands. But I know few of program, so some of my comprehensions maybe incorrect,  just skip them  : )

<h5>UnlockingBIOS</h5>

<blockquote><p><b>AMI Flash Utility</b>  has been updated, so  the command /GAN doesn't work anymore. Thanks for  the-darkvoid, he offers the older Version, it works well: //www.tonymacx86.com/yosemite-laptop-guides/144351-guide-dell-xps-9530-using-clover-uefi-55.html</p>

<p>The <b>UEFITool</b> didn’t work, it seems like a source code that is only about 2Mb. So I searched another one from Internet which is about 8Mb.</p></blockquote>

<h5>Post Installation</h5>

<blockquote>In the line below, the command 3800 should be M3800

<br>sudo cp /Volumes/EFI/EFI/CLOVER/ACPI/origin/DSDT.aml ~/PRECISION-3800-OSX/DSDT/raw/</blockquote>

BTW, I use the USB ethernet card to connect internet, but it caused a problem of the acception to the appstore. I have find the solution from RehabMan, I hope it would be useful <br>//drive.google.com/file/d/0B-ROTctXBhunRlJIUU5NcEpNOEk/view?usp=sharing

**Comment by AustinSMU** [comment]
Thank you for the feedback, I'm glad it worked well for you. I've updated the links to both the AMI Flash Utility and UEFITool. SSDT-rmne, which is RehabMan's NullEthernetInjector, generated during the compilation process should allow you to connect to the App Store. Was that not the case?
