### ISSUE TITLE
Issues with Yosemite 10.10.5

### ISSUE THREAD

**Issue by jv-k** [AustinSMU/PRECISION-M3800-OSX#11]
[config.plist.zip](https://github.com/AustinSMU/PRECISION-M3800-OSX/files/87932/config.plist.zip)

Thanks for the work on the M3800.

I have some issues with all versions that I've installed on my m3800. At the moment I'm on Yosemite 10.11.5. 

If an external monitor is connected via HDMI and the computer sleeps, after wake the main panel doesn't work any more, however the external monitor works.

Another problem is with audio. If I leave the audio jack connected and I boot into Yosemite, there is no sound even though the Headphone device is present. After unplugging the jack there's sound through the internal speakers, and rebooting after unplugging the jack returns normal audio functionality.

Any ideas?

Please let me know if you need any more info.

M3800 late 2013 model / Intel 4702HQ / K1100M HD4600 / Realtek ALC3661 sound

Thanks in advance.

Note:
I tried El Capitan 10.11.2, edited the script to treat it like 10.11 GM for the ioKit patch. No audio and no graphic acceleration. Disabled SIP and tried again without luck.

**Comment by AustinSMU** [comment]
I apologize for the delayed response, work has kept me covered up lately. I've always been aware of the HDMI and audio hot plugging issues. I never spent time resolving those issues, as I rarely utilize them. [syscl](https://github.com/syscl/M3800) user has solved this issue, I just haven't merged it into the repository.
