### ISSUE TITLE
Crashing with dual monitors

### ISSUE THREAD

**Issue by aviz** [AustinSMU/PRECISION-M3800-OSX#3]
Hi,
First i must say that this works grate! the system is very stable with these patches.

There is one thing that dose not work for me and i wondered if you have the same issue.
When i connect one monitor to the hdmi or the mini display port, everything work fine.
but when i connect two monitors at the same time, osx panic and reboot.

Do you have the same behaviour ?

**Comment by seanogdelaney** [comment]
Hi,

I've read elsewhere that this is not supported in OS-X (see the documentation for many thunderbolt docking stations, for example). If you want to connect 2 external monitors to a MacBook Pro, you can use an Apple thunderbolt display, and daisychain your second display. I think Dell also have a thunderbolt display, which may support daisychaining in this way.

One possible alternative is to use a 'Displayport MST hub' to attach multiple screens to a single displayport output. I'm about to test this out (on a 2013 MBP running OS-X, and on an m3800 running Fedora20). I'll let you know how it works out.

If that works on both laptops, I might go ahead with Austin's excellent instructions, and use OS-X on my m3800.

**Comment by AustinSMU** [comment]
I unfortunately do not use dual monitors with this machine, so I haven't attempted a fix for this yet. Keep me posted on the MST hub workaround.

**Comment by seanogdelaney** [comment]
Hi Austin / all,

My MST hub finally arrived. Running Linux on the m3800, it works perfectly. I can run 2 external screens at 2560x1600@60Hz via the mini-DP port. I can simultaneously use the 3200x1800 laptop screen. In theory, I could also run a third external screen in fullHD, using my 1 remaining port on the MST hub. There is just enough bandwidth to do that in the MST hub. I might test that out for the fun some time.

I haven't tried it with my MBP yet, to see if OSX will allow it, but I'm pretty sure it will. I'll let you know if I get time to test that.

**Comment by AustinSMU** [comment]
Good work. I'm curious as to its efficacy in OSX.

**Comment by seanogdelaney** [comment]
Just tested with osx this morning, and failed! According to the mst hub manufacturer, apple don't support multiple mst monitors on their Intel+Nvidia hardware. On AMD, it works. 

Hence, for dual external monitors, it would appear that you need daisychained thunderbolt monitors (I presume that works, though I haven't tested it).

**Comment by syscl** [comment]
Hi, Austin. I rolled back to 10.10 and found that the lid did work after wake! I think it must have something modify in intel's kext. I need a further explore.

**Comment by syscl** [comment]
Just installed AppleIntelFramebufferAzul.kext & AppleIntelHD5000Graphics.kext (come from 10.10) on 10.10.5, and lid wakes after press any keys! But QE/CI is disabled & AppleIntelHD5000Graphics is not loaded. 

Revert to the AppleIntelFramebufferAzul.kext  of 10.10.5, lid doesn't work after wake.

Hence, AppleIntelFramebufferAzul.kext may be the reason why lid cannot work properly!

**Comment by AustinSMU** [comment]
Have you made the appropriate version patch on IOKit?

**Comment by AustinSMU** [comment]
You also need the appropriate Clover kext patches on Azul & HD5000.

**Comment by AustinSMU** [comment]
What's the output of:

md5 /System/Library/Frameworks/IOKit.framework/Versions/Current/

**Comment by syscl** [comment]
IOKit has patched correctly since pixel has uncapped after reboot. 

Using HD5000 (ver 10.10.5) causes kernel panic.

There are a lot of differences between 10.10.0  and 10.10.5 's Azul, I don't know how to figure out the problem.

Austin, do u try ig-platform-id 0x0a260006 to boot OS X? I found that 0x0a2e0008 indeed has the lid wake problem after 10.10.2. (Refer to http://www.tonymacx86.com/yosemite-laptop-support/155651-yosemite-10-10-2-no-wakeup-sleep.html)

Now, I am trying to boot OS X with ig-platform-id 0x0a260006 (still fails till now).

**Comment by AustinSMU** [comment]
I'm using 0x0a260006. Have you considered upgrading to the El Capitan Public Beta? I also wouldn't recommend using kexts from later versions. I haven't updated the repository yet, but I can give you the IOKit patch for El Capitan if you want to try it.

**Comment by syscl** [comment]
Yep, I want to try it, is there something different in the IOKit patch?

Please show your config.plist and script~

Actually,  I have tried EI Captain Beta 1 (using 0x0a2e0008), still the same problem(lid can't wake)

**Comment by AustinSMU** [comment]
For Public Beta 2:

sudo perl -i.bak -pe 's|\xB8\x01\x00\x00\x00\xF6\xC1\x01\x0F\x85|\x33\xC0\x90\x90\x90\x90\x90\x90\x90\xE9|sg' /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit
sudo codesign -f -s - /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit

Your md5 sum should be f0b2d73ac13c9211857af8707db9676d after patching and signing.

Plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>ACPI</key>
<dict>
<key>DSDT</key>
<dict>
<key>Debug</key>
<false/>
<key>DropOEM_DSM</key>
<true/>
<key>Name</key>
<string>DSDT.aml</string>
<key>ReuseFFFF</key>
<false/>
</dict>
<key>SSDT</key>
<dict>
<key>DropOem</key>
<true/>
<key>Generate</key>
<dict>
<key>CStates</key>
<false/>
<key>PStates</key>
<false/>
</dict>
</dict>
<key>SortedOrder</key>
<array>
<string>SSDT-0.aml</string>
<string>SSDT-1.aml</string>
<string>SSDT-2.aml</string>
<string>SSDT-3.aml</string>
<string>SSDT-7.aml</string>
<string>SSDT-8.aml</string>
<string>SSDT-9.aml</string>
<string>SSDT-10.aml</string>
<string>SSDT-11.aml</string>
<string>SSDT-12.aml</string>
<string>SSDT-13.aml</string>
<string>SSDT-14.aml</string>
<string>SSDT-15.aml</string>
<string>SSDT-pr.aml</string>
<string>SSDT-rmne.aml</string>
</array>
</dict>
<key>Boot</key>
<dict>
<key>Arguments</key>
<string>kext-dev-mode=1 dart=0 nv_disable=1</string>
<key>Legacy</key>
<string>LegacyBiosDefault</string>
<key>Log</key>
<false/>
<key>NeverHibernate</key>
<false/>
<key>Secure</key>
<false/>
<key>Timeout</key>
<integer>10</integer>
<key>XMPDetection</key>
<false/>
</dict>
<key>Devices</key>
<dict>
<key>Audio</key>
<dict>
<key>Inject</key>
<string>0</string>
</dict>
<key>FakeID</key>
<dict>
<key>ATI</key>
<string>0x0</string>
<key>IMEI</key>
<string>0x0</string>
<key>IntelGFX</key>
<string>0x04128086</string>
<key>LAN</key>
<string>0x0</string>
<key>NVidia</key>
<string>0x0</string>
<key>SATA</key>
<string>0x0</string>
<key>WIFI</key>
<string>0x0</string>
<key>XHCI</key>
<string>0x0</string>
</dict>
<key>USB</key>
<dict>
<key>FixOwnership</key>
<false/>
<key>Inject</key>
<false/>
</dict>
</dict>
<key>DisableDrivers</key>
<array>
<string>VBoxHfs</string>
</array>
<key>GUI</key>
<dict>
<key>Custom</key>
<dict>
<key>Entries</key>
<array>
<dict>
<key>Disabled</key>
<true/>
<key>FullTitle</key>
<string>UEFI Internal</string>
<key>Hidden</key>
<false/>
<key>Type</key>
<string>Other</string>
</dict>
</array>
</dict>
<key>Hide</key>
<array>
<string>\EFI\BOOT\BOOTX64.EFI</string>
<string>Windows</string>
</array>
<key>Mouse</key>
<dict>
<key>Enabled</key>
<false/>
</dict>
<key>Scan</key>
<dict>
<key>Entries</key>
<true/>
<key>Legacy</key>
<false/>
<key>Tool</key>
<true/>
</dict>
<key>Theme</key>
<string>LightUp</string>
</dict>
<key>Graphics</key>
<dict>
<key>Inject</key>
<dict>
<key>ATI</key>
<false/>
<key>Intel</key>
<true/>
<key>NVidia</key>
<false/>
</dict>
<key>InjectEDID</key>
<false/>
<key>ig-platform-id</key>
<string>0x0a260006</string>
</dict>
<key>KernelAndKextPatches</key>
<dict>
<key>AppleRTC</key>
<false/>
<key>KernelPm</key>
<false/>
<key>KextsToPatch</key>
<array>
<dict>
<key>Comment</key>
<string>Enable TRIM support for non-Apple SSD</string>
<key>Find</key>
<data>
QVBQTEUgU1NEAA==
</data>
<key>Name</key>
<string>IOAHCIBlockStorage</string>
<key>Replace</key>
<data>
AAAAAAAAAAAAAA==
</data>
</dict>
<dict>
<key>Comment</key>
<string>Bootloader Graphics - Second Stage Patch 2</string>
<key>Find</key>
<data>
QYjE6xE=
</data>
<key>Name</key>
<string>IOGraphicsFamily</string>
<key>Replace</key>
<data>
QYjE6zE=
</data>
</dict>
<dict>
<key>Comment</key>
<string>Enable 96MB BIOS, 34MB Framebuffer, 34MB Cursor for Azul framebuffer 0x0a260006</string>
<key>Find</key>
<data>
BgAmCgEDAwMAAAACAAAwAQAAYAA=
</data>
<key>Name</key>
<string>AppleIntelFramebufferAzul</string>
<key>Replace</key>
<data>
BgAmCgEDAwMAAAAGAAAgAgAAIAI=
</data>
</dict>
<dict>
<key>Comment</key>
<string>Enable eDP port 0x00, HDMI port 0x05 for Azul framebuffer 0x0a260006</string>
<key>Find</key>
<data>
AAAIAAIAAAAwAAAAAQUJAAAEAACHAAAA
</data>
<key>Name</key>
<string>AppleIntelFramebufferAzul</string>
<key>Replace</key>
<data>
AAAIAAQAAAAwAAAAAQUJAAAIAACHAAAA
</data>
</dict>
<dict>
<key>Comment</key>
<string>Enable Realtek ALC668 #1</string>
<key>Find</key>
<data>
hAjsEA==
</data>
<key>Name</key>
<string>AppleHDA</string>
<key>Replace</key>
<data>
AAAAAA==
</data>
</dict>
<dict>
<key>Comment</key>
<string>Enable Realtek ALC668 #2</string>
<key>Find</key>
<data>
hQjsEA==
</data>
<key>Name</key>
<string>AppleHDA</string>
<key>Replace</key>
<data>
AAAAAA==
</data>
</dict>
<dict>
<key>Comment</key>
<string>Enable Realtek ALC668 #3</string>
<key>Find</key>
<data>
hBnUEQ==
</data>
<key>Name</key>
<string>AppleHDA</string>
<key>Replace</key>
<data>
aAbsEA==
</data>
</dict>
<dict>
<key>Comment</key>
<string>Enable USB3 after wake for Intel 8 series chipset</string>
<key>Find</key>
<data>
xoDIAAAAAQ==
</data>
<key>Name</key>
<string>AppleUSBXHCI</string>
<key>Replace</key>
<data>
xoDIAAAAAA==
</data>
</dict>
<dict>
<key>Comment</key>
<string>IOBluetoothFamily - Continuity &amp; Hand-off</string>
<key>Find</key>
<data>
SIXAdFwPt0gQg8kEg/kGdVBIiw==
</data>
<key>Name</key>
<string>IOBluetoothFamily</string>
<key>Replace</key>
<data>
PsaDvAIAAAJBvg8AAADpTgAAAA==
</data>
</dict>
</array>
</dict>
<key>SMBIOS</key>
<dict>
<key>BiosReleaseDate</key>
<string>10/18/13</string>
<key>BiosVendor</key>
<string>Apple Inc.</string>
<key>BiosVersion</key>
<string>MBP112.88Z.0138.B02.1310181745</string>
<key>Board-ID</key>
<string>Mac-3CBD00234E554E41</string>
<key>BoardManufacturer</key>
<string>Apple Inc.</string>
<key>BoardSerialNumber</key>
<string>C02416?????FJRJ??</string>
<key>BoardType</key>
<integer>10</integer>
<key>ChassisAssetTag</key>
<string>MacBook-Aluminum</string>
<key>ChassisManufacturer</key>
<string>Apple Inc.</string>
<key>ChassisType</key>
<integer>8</integer>
<key>Family</key>
<string>Macbook Pro</string>
<key>Manufacturer</key>
<string>Apple Inc.</string>
<key>Mobile</key>
<true/>
<key>ProductName</key>
<string>MacBookPro11,2</string>
<key>SerialNumber</key>
<string>C02M????FD56</string>
<key>SmUUID</key>
<string>88678bd5-998e-42c7-8eFF-????????????</string>
<key>Version</key>
<string>1.0</string>
</dict>
<key>SystemParameters</key>
<dict>
<key>InjectKexts</key>
<string>Detect</string>
<key>InjectSystemID</key>
<true/>
</dict>
</dict>
</plist>

**Comment by AustinSMU** [comment]
After 10.10.1 you should be using 0x02a0006.

**Comment by AustinSMU** [comment]
I mean 0x0a260006 ^

**Comment by syscl** [comment]
I use your config.plist (0x0a260006) and 10.10.0 just boot smoothly without any graphics glitches! Also QE/CI works. The new edition of your plist is more concise and clear!

Next step, I'll jump into EI Captain and see how this configuration work!

**Comment by syscl** [comment]
EI Captain Beta1 & 2 and 10.10.2 stops at verbose mode with 0x0a260006(patched dsdt, ssdt, iokit).

**Comment by syscl** [comment]
10.10.2 & 10.11.1 & 10.11.2: 

RM inject(0412) + 0x0a260006 Azul and HD 5000 dosen't load.

RM inject(0412) + 0x0a260006 + FakeID 04128086(clover) can't boot out of verbose mode.

0x0a260006 + FakeID 04128086(clover) can't boot out of verbose mode (I can hear the voice by changing the volume and when I cover and uncover the lid, the lid wakes up in verbose mode)

0x0a2e0008 + 0x04128086 can drive the HD4600. 

the md5 of patched IOKit of 10.10.2 is 3cd0915806ad064759e156778b152973

**Comment by AustinSMU** [comment]
Just use a version you have the least issues with...

**Comment by syscl** [comment]
Tested 10.10.2 with 0x0a260006 , all goes well!! And I found the reason why 0a260006 can't take effect: Azul & HD5000 need to be loaded (use without caches), and then rebuild caches, changes 0a2e0008 to 0a260006,  lid wakes after sleep! nearly the same as xps9530 now.

Now, i will test EI Captain. (10.10.5 is OK !)

And, do you have problems with headphones after reboot?

Thank you , RehabMan and darkvoid again ! Cheers!
