### ISSUE TITLE
QE/CI with the integrated HD4600

### ISSUE THREAD

**Issue by jeromesavin** [AustinSMU/PRECISION-M3800-OSX#4]
Hi,

Before anything else, many ... many thanks for your great job.
Your procedure is clear and quite easy.

I have one question about the resulting OSX configuration, is QE/CI working for you with the procedure you explain ?

As I'm french and my HW configuration may differ from yours, I would like to know if it is the same for you.

That's the last thing missing for me to be fully operationnal on my first hackintosh.

Last question, are you going to update the procedure with the last Clover versions, or it doesn't change anything. 

Many thanks, sincerely.

Jerome

**Comment by AustinSMU** [comment]
Yes, I have full graphics acceleration. If you've uncapped the pixel clock, and applied the correct Clover patches using my instructions, QE/CI will fully functional. I will likely update Clover when 10.10.4 rolls out. I haven't kept up with the last several revisions, but it should be safe to update.
