### ISSUE TITLE
Question about the 10.10.3 IOKIT while patched and signed

### ISSUE THREAD

**Issue by jeromesavin** [AustinSMU/PRECISION-M3800-OSX#5]
Hi,

I think there is a little problem on DELLM3800.sh script (line 257)

OK, let's say I start from a 10.10.3 outofthebox IOKIT and play these commands :
# Let's work in a temporary directory

   MacBook-Pro: jeromesavin$ sudo bash
   Password:
   bash-4.3# cp /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit /tmp
   bash-4.3# cd /tmp
   bash-4.3# ls -l IOKit
   -rwxr-xr-x  1 root  wheel  1437360 24 jui 10:32 IOKit
   bash-4.3# md5 -q IOKit 
   29d7632362b2fa4993156717671a5642 **<== This is the sum you expect for a clean/unpatched 10.10.3 IOKit**
# Now I patch the 10.10.3 IOKIT

   bash-4.3# perl -i.bak -pe 's|\xB8\x01\x00\x00\x00\xF6\xC1\x01\x0F\x85|\x33\xC0\x90\x90\x90\x90\x90\x90\x90\xE9|sg' /tmp/IOKit 
   bash-4.3# ls -l IOK*
   -rwxr-xr-x  1 root  wheel  1429328 24 jui 10:35 IOKit
   -rwxr-xr-x  1 root  wheel  1429328 24 jui 10:33 IOKit.bak
   bash-4.3# md5 -q IOKit IOKit.bak 
   4bd81492fd13e905ef10719ef391e8a0  **<== this is the sum you expect for a patched but _unsigned_ 10.10.3 IOKit**
   29d7632362b2fa4993156717671a5642
# Now I sign the patched 10.10.3 IOKit

   bash-4.3# codesign -f -s - IOKit
   IOKit: replacing existing signature
   bash-4.3# ls -l IOK*
   -rwxr-xr-x  1 root  wheel  1437360 24 jui 10:36 IOKit
   -rwxr-xr-x  1 root  wheel  1429328 24 jui 10:33 IOKit.bak
   bash-4.3# md5 -q IOKit IOKit.bak 
   a5c66f2de803df41a896e7f8096938d7 **<== !! THIS IS NOT THE SUM YOU EXPECT FOR A    PATCHED AND SIGNED 10.10.3 IOKIT !!**
   29d7632362b2fa4993156717671a5642
   bash-4.3# 

As my resulting patched/signed IOKit sum is not the same the one you expect on line 257, my questions are :
- Is you sum "a045c1ac523fece1f1b083b2c5ee842c" expected on line 257 the good one (or "a5c66f2de803df41a896e7f8096938d7") ?
- Did I do something wrong ?

Thanks for you help.

Jerome

**Comment by AustinSMU** [comment]
Have you tried running my automated IOKit patch? If so, what was the result?

**Comment by AustinSMU** [comment]
The correct sum is a045...
