### ISSUE TITLE
Replacing Linux with OS-X on m3800

### ISSUE THREAD

**Issue by seanogdelaney** [AustinSMU/PRECISION-M3800-OSX#6]
Hi Austin,

Outstanding work. I can't imagine how long it would have taken me to put these instructions together. I have exactly the hardware configuration you describe in the README, so I'm tempted to try this.

Before I do, I was wondering if you had any comments on starting from a Linux install. Obviously I could install Windows and work from there. However, for reasons I won't bore you with, that will be difficult in my case.

Thanks, and kudos.

Sean

**Comment by AustinSMU** [comment]
Is your BIOS unlocked yet? I haven't had any success using a comparability layer tool in running the BIOS flashing utility. The only other recommendations I can make would be to either build a live bootable Windows USB, or install Windows on an external hard drive.

**Comment by AustinSMU** [comment]
Compatibility*

**Comment by seanogdelaney** [comment]
No, I haven't touched the BIOS (haven't even checked it's up to date yet). 

I think the live USB would be the way to go. I might take the opportunity to clone my SSD, while it's not in use. Always nice to me able to reinstall linux if things don't work out.

BTW, am I correct in saying that this works with the existing wifi chip?

Thanks,

Sean

**Comment by AustinSMU** [comment]
If you're talking about the Intel Wireless-AC 7260, then no. You will need to replace it with the Broadcom chipset I have recommended.

**Comment by syscl** [comment]
HI Austin! Great job!

I'm glad to tell I succeed in OSX 10.10.4 with A09 unlocked BIOS. However there's something strange:

1) Bios: TPM Security couldn't be found in Security even when I rolled back to A07 version.
2) When lid and cover again, the screen can't wake both in 10.10.2 and 10.10.4. But in 10.10.4, it will be sightly different for it can lid and cover and function normally in the first time. And the system is running in this period for the music still goes on.
3) Headphone outputs nothing when I plug it in and reboot the system until I reinstall the kexts again.

My configuration is : 
Dell M3800 with i7-4712HQ, 4Gx2 DDR3 1600, Sharp touch screen with 3200*1600, DW1560, A09 Bios.

To power the HD4600, I just add 0x0a2e0008, 0x04128086 and patch the IOKit. 

Hope you can give me some hints to solve the problems above. Thanks in advance!

**Comment by AustinSMU** [comment]
Don't worry about TPM security, it must have been phased out after A06. Did the lid function properly in 10.10.3, and does using the power button to wake the screen work? As for your audio, try deleting the ALC668 and CodecCommander kexts, rebuilding kext cache, reboot, rerun my hda patch, rebuild kext cache, reboot. You can also try injecting those kexts using Clover. I will be updating the repository sometime next week for 10.10.4 and the public beta of El Capitan, and try to address some of these other issues if time permits.

**Comment by AustinSMU** [comment]
Also, you can try using darkvoid's XPS-9530 hda patch, as he updates his repository quite a bit more frequently than I do.

**Comment by syscl** [comment]
Thx for your reply! I haven't try 10.10.3 yet. I use the power button to wake it up, but it fails to wake the screen up, it just wake the system up and I think the system is running normally for I can hear the volume change after F2 & F3. 

I apply the darkvoid's iokit-patch & hda-patch in 10.10.4 but I think there's nothing different as your script. 

And also, the number of ssdt I dumped in Clover or Ubuntu is 15, that means I need to rename my SSDT-14.aml to SSDT-15.aml to suit your script, can you please show me your raw dsdt and ssdt. And  do you lid function properly ?

**Comment by AustinSMU** [comment]
Are you sure you only dumped 15 SSDT's? You should have SSDT-0 through SSDT-15, which yields 16 total. I suspect you have an incorrect BIOS setting if you are only generating 15 tables, and is likely the cause of your other issues as well. ACPI tables are VERY sensitive to changes in BIOS settings. I would recommend resetting your BIOS to default, making only the changes I have indicated, re-dumping your tables using Clover (not Linux), rerunning the patches and then replacing your currently patched tables in the EFI partition. The script for decompiling, patching and compiling the tables is based on a Clover dump. You can also try using the tables I have included that I patched by hand using pristine Linux tables.

**Comment by syscl** [comment]
I know what you mean, my SSDT is SSDT-0 through SSDT-14. So after check the OEM table, I rename SSDT-14 to SSDT-15. Now I have to reset my bios first and can you show me your raw dsdt and ssdt?

**Comment by AustinSMU** [comment]
Are you receiving errors while running the script to decompile, patch and recompile your ACPI tables?

**Comment by AustinSMU** [comment]
You should have 0-15, not 0-14.

**Comment by syscl** [comment]
No, after rename the SSDT-14 to SDT-15, the script runs right and all patches have applied for the changes are applied to those ssdt. (I also added acpi100 patch to DSDT and modify "Windows 2001" to "Darwin" seems useless so I remove the change and only use your script!)

**Comment by AustinSMU** [comment]
The fact that you are having to rename your tables to fit the numbering convention is likely indicative of an incorrectly configured BIOS. This process is very specific, and very difficult to troubleshoot if an alternate process is being used to generate, decompile, patch and recompile the tables.

**Comment by AustinSMU** [comment]
Adding extra patches and modifying existing patches arbitrarily without the necessary understanding is adding immeasurable complexity to an already challenging puzzle. It's impossible for me to help you if you haven't followed the procedure exactly, which you obviously haven't.

**Comment by syscl** [comment]
Hi, Austin! I've followed your guide nearly exactly expect TPM Security. And even flashed back the Bios to A07 as you. And also the system is 10.10.2. And I've just found something interesting in the SSDT. The ssdt I lost is the one with OEM table 'PROC'!! I open that file with MaciASL and found "TPM 1.2 Device" in it which may mean that the Bios I use may have some problem?

**Comment by AustinSMU** [comment]
That is strange indeed. The only thing I could recommend is to try rolling back to A06 if you can find it.

**Comment by syscl** [comment]
OK! Which bios do you use now? The only version I can find now is A07.

Again, Thank you for your reply :)

**Comment by AustinSMU** [comment]
Not a problem, I wish I could be more help but your missing TPM is quite peculiar. I'm still running A07. Have you tried reaching out to darkvoid?

**Comment by AustinSMU** [comment]
If I remember correctly, there is an A09 out now - have you tried that version yet?

**Comment by syscl** [comment]
Yes! Both A07 and A09 I've tried! I'm now running the A09 bios. And dell moved away any previous version of bios on its ftp.
