### ISSUE TITLE
Questions before I can start!

### ISSUE THREAD

**Issue by Byron657** [AustinSMU/PRECISION-M3800-OSX#7]
Hello, first of all Austin congratulation for this project, you are a monster! I've got some question before I can start the process:

1-I don't understand if I can only use the integrated graphic or I can use also the NVIDIA quadro.
2-Do I have to replace the Wi-Fi card?
3-Can I dual boot Windows 10 and Yosemite with MultiBeast or the BIOS will become not compatible with Win 10? (I need also Windows 10)
4-Do the touchscreen will work?

Thanks in advance if you'll help! Have a nice day and keep up good work :)

**Comment by AustinSMU** [comment]
Hi Byron,

Thank you for the feedback, it's always nice to know when the work is appreciated. To answer your inquiries:
1. Only the integrated HD4600 can be utilized in OSX. There is no support in OSX for video chipsets utilizing Optimus.
2. If your machine came with the Intel Wireless-AC 7260, then you will need to replace it as there is no support in OSX for Intel WiFi.
3. If you used my guide to install OSX, you shouldn't be using Multibeast, but yes you can dual-boot. I'm running OSX, Ubuntu and Windows.
4. Yes; see the link at the very end of the guide for UPDD.

**Comment by Byron657** [comment]
Thanks very much for the quick reply! I was afraid that the quadro wouldn't work with OS X because I saw the specs of the macbooks and they all got an Intel graphic chip, except for a model of macbook pro that got an AMD chip. For what you know not even "El Capitan" got the support for Nvidia Optimus?
The system is stable even with using the integrated graphic? And last, sorry if I give you too many questions, I can MultiBeast at the end of your guide or I have to follow another process?

Thanks very much in advance :)

**Comment by AustinSMU** [comment]
It is unlikely that any version of OSX will support Optimus graphics. The system is very stable with full graphics acceleration including QE/CI using the HD4600. You should not be using Multibeast on the M3800. Follow the instructions exactly in the Wiki, and make sure to read the entire guide before you begin – the installation is very specific. If you don't, it will be impossible for me to help you troubleshoot any issues you might come across during post-installation.

**Comment by Byron657** [comment]
Ok thanks, I was asking for multibeast because I can't see any reference do dual/triple boot in the guide and for my knowledge people used to install multibeast to dual boot. So after I'll install OS X I can run the W10 installation USB and install it in another partition? And I can choose the OS directly in the BIOS when booting or what? Sorry for asking too much questions, it's because I need windows too to work so dual boot it's a priority for me :)

**Comment by AustinSMU** [comment]
You can use the Disk Utility to manually repartition your drive. You need to make sure and install UEFI Windows so that it's bootable from the Clover menu. Make sure when you partition your drive to use a filesystem other than FAT32, or OSX will create a hybrid-MBR, and you won't be able to install UEFI Windows.
