### ISSUE TITLE
qe/ci notworking  in yosemite 10.10.4

### ISSUE THREAD

**Issue by ghost** [AustinSMU/PRECISION-M3800-OSX#8]
hi, AustionSMU,

i update my laptop with yosemite 10.10.4 .
i use your CLOVER folder to replace the EFI/CLOVER  and boot with full resolution .
but find qe/ci is not working . 
Is there still no driver for this version ? or maybe some steps wrong ?

thanks

**Comment by AustinSMU** [comment]
Did you run the --patch-iokit shell command to unlock the pixel clock?

**Comment by ghost** [comment]
yes, i run --update successful, then i skip the dsdt patch steps, and go on with 
the --patch-iokit and --patch-hda , run kext utility to fix permission.

it reboot with 3200*1800 resolution , recognize  the hd4600 and the sound card works when i playing some music ,but no qe effect. 
then i run --patch-iokit again ,but it told me already patched.

**Comment by AustinSMU** [comment]
Download KextWizard. Open it, and select the "Loaded Kexts" tab. Are IntelAzulFramebuffer and AppleIntelHD5000Graphics both loaded?

**Comment by ghost** [comment]
sorry , i missed some steps.

the first reboot after  run kext utility is not succeed to go to the desktop.
so i force to shutdown it . and reboot  it through the USB CLOVER ,and it go in desktop succeed.
and I install the  FakePCIID HD4600/HD4400  driver through the "MacPois0n Yosemite v2.9 .pkg"
and reboot again and it boot into desktop succeed with 3200*1800 resolution, but without qe enabled.
I found Kexts Backup folder created by  "MacPois0n Yosemite v2.9 .pkg", I found "AppleIntelFramebufferAzul.kext" and "AppleIntelHD5000Graphics.kext" in it .
I install Kext Wizard and find "AppleIntelFramebufferAzul.kext" and "AppleIntelHD5000Graphics.kext" are all loaded and their version is 10.0.6. 
I think it had patched the two kexts but some args not set properly  with  10.10.4 .
is there some steps to patch the two kexts to work properly ? 

thank you very much.

**Comment by AustinSMU** [comment]
The only patches that need to be applied to those kexts are done by Clover. If you follow the wiki exactly, none of these issues should be happening. You have to perform the steps exactly as they are outlined, or you end up with issues like this. I also mention that it is almost impossible for me to help troubleshoot any issues unless the steps are performed correctly, let alone introducing more variables, like "MacPoison" kext patches. The only advice I can offer is to start my guide over from the beginning, and do it correctly.

**Comment by ghost** [comment]
ok, I will follow your step and try again .
thanks for your patience.

**Comment by AustinSMU** [comment]
Read the last several comments to find the solution:

http://www.insanelymac.com/forum/topic/305488-guide-dell-precision-m3800-3200x1800-qhd-touch-i7-47x2hq-intelhd4600-quadrok1100m-alc668/page-2
